#pragma once

#define PF_DEEP_COLOR_AWARE 1

#include "AEConfig.h"
#include "AE_Effect.h"
#include "AE_EffectCB.h"
#include "AE_EffectCBSuites.h"
#include "AE_EffectPixelFormat.h"
#include "AE_EffectSuites.h"
#include "AE_Macros.h"
#include "AEGP_SuiteHandler.h"
#include "AEFX_SuiteHelper.h"
#include "Param_Utils.h"
#include "entry.h"

#define KG_LAYOUTGRID_EFFECT_NAME "kg_LayoutGrid"
#define KG_LAYOUTGRID_EFFECT_MATCHNAME "kg_LayoutGrid"
#define KG_LAYOUTGRID_EFFECT_CATEGORY "KG_plugins"
#define KG_LAYOUTGRID_MAJOR_VERSION 1
#define KG_LAYOUTGRID_MINOR_VERSION 0
#define KG_LAYOUTGRID_BUG_VERSION 0
#define KG_LAYOUTGRID_STAGE_VERSION PF_Stage_DEVELOP
#define KG_LAYOUTGRID_BUILD_VERSION 1
#define KG_LAYOUTGRID_EFFECT_VERSION PF_VERSION(KG_LAYOUTGRID_MAJOR_VERSION, KG_LAYOUTGRID_MINOR_VERSION, KG_LAYOUTGRID_BUG_VERSION, KG_LAYOUTGRID_STAGE_VERSION, KG_LAYOUTGRID_BUILD_VERSION)

enum {
	KG_LAYOUTGRID_INPUT = 0,
	KG_LAYOUTGRID_COLUMNS_TOPIC_START,
	KG_LAYOUTGRID_COL_COUNT,
	KG_LAYOUTGRID_COL_MARGIN,
	KG_LAYOUTGRID_COL_GUTTER,
	KG_LAYOUTGRID_COLUMNS_TOPIC_END,
	KG_LAYOUTGRID_ROWS_TOPIC_START,
	KG_LAYOUTGRID_ROW_COUNT,
	KG_LAYOUTGRID_ROW_MARGIN,
	KG_LAYOUTGRID_ROW_GUTTER,
	KG_LAYOUTGRID_ROWS_TOPIC_END,
	KG_LAYOUTGRID_STYLE_TOPIC_START,
	KG_LAYOUTGRID_DISPLAY_MODE,
	KG_LAYOUTGRID_LINE_WIDTH,
	KG_LAYOUTGRID_BAND_OPACITY,
	KG_LAYOUTGRID_COLUMN_COLOR,
	KG_LAYOUTGRID_ROW_COLOR,
	KG_LAYOUTGRID_SPIRAL_COLOR,
	KG_LAYOUTGRID_STYLE_TOPIC_END,
	KG_LAYOUTGRID_GUIDES_TOPIC_START,
	KG_LAYOUTGRID_GUIDE_MODE,
	KG_LAYOUTGRID_APPLY_GUIDES,
	KG_LAYOUTGRID_LOCK_GUIDES,
	KG_LAYOUTGRID_UNLOCK_GUIDES,
	KG_LAYOUTGRID_CLEAR_ALL,
	KG_LAYOUTGRID_GUIDES_TOPIC_END,
	KG_LAYOUTGRID_NUM_PARAMS
};

enum {
	COL_COUNT_DISK_ID = 1,
	COL_MARGIN_DISK_ID,
	COL_GUTTER_DISK_ID,
	ROW_COUNT_DISK_ID,
	ROW_MARGIN_DISK_ID,
	ROW_GUTTER_DISK_ID,
	DISPLAY_MODE_DISK_ID,
	LINE_WIDTH_DISK_ID,
	BAND_OPACITY_DISK_ID,
	COLUMN_COLOR_DISK_ID,
	ROW_COLOR_DISK_ID,
	SPIRAL_COLOR_DISK_ID,
	GUIDE_MODE_DISK_ID,
	APPLY_GUIDES_DISK_ID,
	LOCK_GUIDES_DISK_ID,
	UNLOCK_GUIDES_DISK_ID,
	CLEAR_ALL_DISK_ID,
	COLUMNS_TOPIC_START_DISK_ID,
	COLUMNS_TOPIC_END_DISK_ID,
	ROWS_TOPIC_START_DISK_ID,
	ROWS_TOPIC_END_DISK_ID,
	STYLE_TOPIC_START_DISK_ID,
	STYLE_TOPIC_END_DISK_ID,
	GUIDES_TOPIC_START_DISK_ID,
	GUIDES_TOPIC_END_DISK_ID
};

struct KgLayoutGridGlobal {
	AEGP_PluginID plugin_id = 0;
};

extern "C" {
DllExport PF_Err EffectMain(
	PF_Cmd cmd,
	PF_InData* in_data,
	PF_OutData* out_data,
	PF_ParamDef* params[],
	PF_LayerDef* output,
	void* extra);
}
